- name: Install and configure Nginx
  hosts: webserver
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Enable Nginx
      systemd:
        name: nginx
        enabled: yes

    - name: Start Nginx
      systemd:
        name: nginx
        state: started

